on:
  push:
    branches: master
    paths:
      - "**.py"
  pull_request:
    paths:
      - "**.py"
name: quality checks

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.1
    - uses: actions/setup-python@v4.7.1
      with:
        python-version: "3.11"
    - uses: pre-commit/action@v3.0.0
